In [2]:
import numpy as np

p = np.array([[0,0.5,0,0,0,0.5,0],
              [0,0,0.8,0,0,0,0.2],
              [0,0,0,0.6,0.4,0,0],
              [0,0,0,0,0,0,1.0],
              [0.2,0.4,0.4,0,0,0,0],
              [0.1,0,0,0,0,0.9,0],
              [0,0,0,0,0,0,1]])
p

array([[ 0. ,  0.5,  0. ,  0. ,  0. ,  0.5,  0. ],
       [ 0. ,  0. ,  0.8,  0. ,  0. ,  0. ,  0.2],
       [ 0. ,  0. ,  0. ,  0.6,  0.4,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ],
       [ 0.2,  0.4,  0.4,  0. ,  0. ,  0. ,  0. ],
       [ 0.1,  0. ,  0. ,  0. ,  0. ,  0.9,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [3]:
reward = np.array([[-2],[-2],[-2],[10],[1],[-1],[0]], dtype=np.float64)
reward

array([[ -2.],
       [ -2.],
       [ -2.],
       [ 10.],
       [  1.],
       [ -1.],
       [  0.]])

In [4]:
c_state = np.array([[1],[0],[0],[0],[0],[0],[0]], dtype=np.float64).T
c_state

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
test=c_state
for i in range(50):
    test=np.dot(test,p)
    if i%10==0:
        print(test)


[[ 0.   0.5  0.   0.   0.   0.5  0. ]]
[[ 0.03493676  0.02311374  0.02459908  0.01600674  0.01067116  0.31173931
   0.57893323]]
[[ 0.02197783  0.01400113  0.0142274   0.00894239  0.00596159  0.19805656
   0.7368331 ]]
[[ 0.01393433  0.00887021  0.00900529  0.00565508  0.00377006  0.12559826
   0.83316676]]
[[ 0.00883613  0.00562476  0.00571031  0.00358586  0.00239057  0.07964558
   0.8942068 ]]


In [6]:
np.dot(p,reward)

array([[-1.5],
       [-1.6],
       [ 6.4],
       [ 0. ],
       [-2. ],
       [-1.1],
       [ 0. ]])

In [7]:
np.dot(c_state,p)

array([[ 0. ,  0.5,  0. ,  0. ,  0. ,  0.5,  0. ]])

---------------------------------------------------------------
value function

--------------------------------

bellman equation



In [582]:
#value_function when decay 0.9
np.dot(np.linalg.inv(np.eye(7)-0.90*p),reward)

array([[ -5.01272891],
       [  0.9426553 ],
       [  4.08702125],
       [ 10.        ],
       [  1.90839235],
       [ -7.63760843],
       [  0.        ]])

In [534]:
#Mathematically convenient?????
np.dot(np.linalg.inv(np.eye(7)-1*p),reward)

LinAlgError: Singular matrix